### ISSUE TITLE
Image Caption dan User Experience yang kurang nyaman

### ISSUE THREAD

**Issue by radinalsuryaatmaja** [stratum-project/ignite#23]
jadi kami agak kurang nyaman dengan cara memasukkan image caption ke dalam gambar

Terkadang kayak nge-hang

Pada saat ketik di image caption, kebiasaan selanjutnya adalah melakukan enter , tetapi terkadang tidak bisa aktif typing nya

lihat masalah pada video dibawah ini

https://drive.google.com/file/d/15GhHIDLJfMN8nPmb0t0dtwnghcpYUIh6/view?usp=sharing

---

**yang benar seharusnya**

https://drive.google.com/file/d/1S0hVWQ6ZHHyKe2UqLdLYBqB0XC0ZxjRv/view?usp=sharing

UX tentang image dan image caption persis kayak medium.com

**Comment by nevrending** [comment]
Fixed #23

This is a known issue with Froala atm
Refer to https://github.com/froala/wysiwyg-editor/issues/3351

Applied a temporary fix

**Comment by nevrending** [comment]
Just a friendly reminder, **please do note** that the Medium editor can only be used as a reference, that being said it's just not possible to (re)produce an exact replication of their features and behaviors since it's a closed-source editor that they developed themselves while we, as in our agreement, are using a third party software.

**Comment by radinalsuryaatmaja** [comment]
OKE
